language: objective-c
osx_image: xcode9.1
xcode_project: FrameWork/LFLiveKit.xcodeproj
xcode_scheme: LFLiveKit

before_install:
- gem install xcpretty -N --no-ri --no-rdoc
- SIMULATOR_ID=$(xcrun instruments -s devices | grep -io "$SIMULATOR \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
- pod repo update

script:
- set -o pipefail
- open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
- xcodebuild clean build -project FrameWork/LFLiveKit.xcodeproj -scheme LFLiveKit -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
